### PR TITLE
Vendor golang package.

### PR DESCRIPTION
**Pull request by jmcarp**
* Vendor golang package
* Use empty array instead of empty hash for empty dependencies

### CODE REVIEW

**Comment by alext** [comment]
Hi @jmcarp 

I'm not sure I follow what these changes are doing, and how this actually vendors the golang package.

Could you describe what the problem is that this is aiming to solve.

thanks,
Alex

**Comment by jmcarp** [comment]
Sure! The problem is that every bosh release that packages golang had to copy and paste a golang package and blobs, and users wind up compiling a bunch of duplicate packages. Bosh recently introduced a `vendor-package` command, along with a set of common packages, so that many releases can vendor those packages, without copying and pasting code and blobs or compiling duplicates. I followed the process at https://bosh.io/docs/package-vendoring.html, using the package at https://github.com/bosh-packages/golang-release.

Separately, I switched empty package dependencies from `{}` to `[]` so that we can build releases with the latest bosh cli.

**Comment by jmcarp** [comment]
Does this make sense @alext @bandesz? The idea is to use pre-made packages for common things like languages to avoid copying and pasting scripts, and uploading multiple copies of the same blobs.

**Comment by alext** [comment]
Hi @jmcarp I need to do some reading up on bosh vendored packages to understand the implications for our workflows etc. From a cursory reading, I think this will mean that the boshrelease will no longer be self-contained, but instead require the golang package to have been previously uploaded to the bosh director...

**Comment by jmcarp** [comment]
@alext: bosh package vendoring copies an existing package into a release. It fetches any required blobs and adds them to the release blobstore. When the release is packed into a tarball, it contains blobs for the package. You can check out an example in the wild at http://bosh.io/releases/github.com/cloudfoundry-community/prometheus-boshrelease?all=1. If you grab the tarball, you'll find blobs for the vendored golang package.

**Comment by alext** [comment]
Hi @jmcarp 

Thanks for pointing us at the `vendor-package` feature. I think it's something we'll want to look at using in the future, but it's not something we can spend the time on at present. We'll probably pick this up the next time we do some work on our bosh releases workflow, but at present I don't know when that will be.

In the meantime, I don't think it's useful to keep this PR open, so I'm going to close it.

**Pull request closed without merging**
